'use strict';

const path = require('path');

// Carregar variáveis de ambiente
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

module.exports = {
  apps: [
    {
      name: 'webhook-whatsapp-meta',
      script: './processwhatsapp.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      error_file: path.join(__dirname, 'logs/webhook-whatsapp-meta.error.log'),
      out_file: path.join(__dirname, 'logs/webhook-whatsapp-meta.out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3001,
        WS_PORT: process.env.WS_PORT || 3003,
        // Passar todas as variáveis de ambiente
        DB_CLIENT: process.env.DB_CLIENT,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME,
        WHATSAPP_FLOW_PRIVATE_KEY_PATH: process.env.WHATSAPP_FLOW_PRIVATE_KEY_PATH,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        WHATSAPP_GRAPH_VERSION: process.env.WHATSAPP_GRAPH_VERSION,
        WHATSAPP_TEMPLATE_NAME: process.env.WHATSAPP_TEMPLATE_NAME,
        WHATSAPP_TEMPLATE_LANG: process.env.WHATSAPP_TEMPLATE_LANG,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3001,
        WS_PORT: 3003,
        // Passar todas as variáveis de ambiente
        DB_CLIENT: process.env.DB_CLIENT,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME,
        WHATSAPP_FLOW_PRIVATE_KEY_PATH: process.env.WHATSAPP_FLOW_PRIVATE_KEY_PATH,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        WHATSAPP_GRAPH_VERSION: process.env.WHATSAPP_GRAPH_VERSION,
        WHATSAPP_TEMPLATE_NAME: process.env.WHATSAPP_TEMPLATE_NAME,
        WHATSAPP_TEMPLATE_LANG: process.env.WHATSAPP_TEMPLATE_LANG,
      },
    },
    {
      name: 'app-server',
      script: './app.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      error_file: path.join(__dirname, 'logs/app-server.error.log'),
      out_file: path.join(__dirname, 'logs/app-server.out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000,
        WS_PORT: process.env.WS_PORT || 3003,
        // Passar todas as variáveis de ambiente
        DB_CLIENT: process.env.DB_CLIENT,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME,
        WHATSAPP_FLOW_PRIVATE_KEY_PATH: process.env.WHATSAPP_FLOW_PRIVATE_KEY_PATH,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        WHATSAPP_GRAPH_VERSION: process.env.WHATSAPP_GRAPH_VERSION,
        WHATSAPP_TEMPLATE_NAME: process.env.WHATSAPP_TEMPLATE_NAME,
        WHATSAPP_TEMPLATE_LANG: process.env.WHATSAPP_TEMPLATE_LANG,
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
        WS_PORT: 3003,
        // Passar todas as variáveis de ambiente
        DB_CLIENT: process.env.DB_CLIENT,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME,
        WHATSAPP_FLOW_PRIVATE_KEY_PATH: process.env.WHATSAPP_FLOW_PRIVATE_KEY_PATH,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        WHATSAPP_GRAPH_VERSION: process.env.WHATSAPP_GRAPH_VERSION,
        WHATSAPP_TEMPLATE_NAME: process.env.WHATSAPP_TEMPLATE_NAME,
        WHATSAPP_TEMPLATE_LANG: process.env.WHATSAPP_TEMPLATE_LANG,
      },
    },
    {
      name: 'frontend-dev',
      script: 'npm',
      args: 'run dev',
      cwd: path.join(__dirname, '../frontend'),
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 20,
      min_uptime: '10s',
      restart_delay: 2000,
      error_file: path.join(__dirname, 'logs/frontend-dev.error.log'),
      out_file: path.join(__dirname, 'logs/frontend-dev.out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'development',
      },
    },
  ],

  deploy: {
    production: {
      user: process.env.DEPLOY_USER || 'deploy',
      host: process.env.DEPLOY_HOST || 'your-server.com',
      ref: 'origin/main',
      repo: 'git@github.com:your-repo/your-project.git',
      path: '/var/www/your-app',
      'post-deploy': 'npm install && npm run build',
    },
  },
};
